apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-service
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-service
  template:
    metadata:
      labels:
        app: blog-service
    spec:
      containers:
        - name: blog-service
          image: {{ .Values.image }}
          ports:
            - containerPort: {{ .Values.port }}