apiVersion: v1
kind: Service
metadata:
  name: blog-service
  namespace: {{ $.Values.global.namespace }}
spec:
  ports:
    - port: {{ $.Values.blog-service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: blog-service