apiVersion: v1
kind: Service
metadata:
  name: blog-service
spec:
  ports:
    - port: {{ .Values.blog-service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: blog-service