apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: {{ $.Values.global.namespace }}
spec:
  ports:
    - port: {{ $.Values.gateway-service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: gateway-service  