apiVersion: v1
kind: Service
metadata:
  name: eureka-service
spec:
  ports:
    - port: {{ .Values.eureka-service.port }}
      targetPort: 8761
      protocol: TCP
      name: http
  selector:
    app: eureka-service